spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.152.129
    port: 5672
    username: nicole
    password: fhy1997
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  xixihahaha
